


spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/bank
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: bank_service

logging:
  level:
    root: INFO  #  Уровень логирования по умолчанию для всех пакетов (INFO, DEBUG, WARN, ERROR, TRACE)
    com.example.yourproject: DEBUG  #  Уровень логирования для вашего пакета
    org.springframework.web: INFO  # Уровень логирования для Spring Web
    #  Чтобы видеть SQL запросы, добавьте:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/ # Адрес Eureka Server
    register-with-eureka: true

